appDomain: http://localhost

requestRouter:
  port: 8080
  name: prestoRouter
  historySize: 1000

dataStore:
  jdbcUrl: jdbc:mysql://0.0.0.0:3306/prestogateway
  user: test
  password: password
  driver: com.mysql.cj.jdbc.Driver

cachingDatabase:
  databaseType: redis
  host: dev-presto-gateway-redis.n4lngy.clustercfg.use1.cache.amazonaws.com
  port: 6379
  bucket: 6si-loki-dev

server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

modules:
  - com.lyft.data.query.processor.module.QueryProcessorProviderModule
  - com.lyft.data.gateway.ha.module.HaGatewayProviderModule
  - com.lyft.data.gateway.ha.module.ClusterStateListenerModule

managedApps:
  - com.lyft.data.gateway.ha.GatewayManagedApp
  - com.lyft.data.gateway.ha.clustermonitor.ActiveClusterMonitor
  - com.lyft.data.query.processor.ProcessorManagedApp

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.lyft: DEBUG
    # com.lyft.data.server: INFO
    # com.lyft.data.query.processor.caching: INFO
    # com.lyft.data.gateway: INFO
    # com.lyft.data.gateway.ha.clustermonitor.ActiveClusterMonitor: WARN

  appenders:
    - type: console
    - type: file
      currentLogFilename: /var/log/prestoproxy/prestoproxy-java.log
      archivedLogFilenamePattern: /var/log/prestoproxy/prestoproxy-java-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 100MB